version: '3.16'

networks:
  expense-local:
    name: expense-local
services:
  mysql_local:
    platform: linux/amd64
    image: mysql:5.7.39-debian
    container_name: expense_mysql_database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=America/Araguaina
    networks:
      - expense-local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 40s
      retries: 10
    command: ['mysqld', '--sql-mode=NO_ENGINE_SUBSTITUTION']
  expense_database:
    stdin_open: true
    platform: linux/amd64
    image: expense-local/database_local:1.0.0
    container_name: database
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql_local
    env_file:
      - envs/database.env
    environment:
      - TZ=America/Araguaina
    networks:
      - expense-local
  expense-api:
    platform: linux/amd64
    image: expense-local/api_local:1.0.0
    container_name: api
    build:
      context: ./
      dockerfile: API.Dockerfile
    depends_on:
      - expense_database
    env_file:
      - .env
    environment:
      - TZ=America/Araguaina
    ports:
      - 3031:3031
    networks:
      - expense-local
    
